name: Node.js CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Navigate to project folder
          cd ~/nodejsapp
          
          # Load NVM and Node environment
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          
          # Update code and dependencies
          git fetch --all
          git reset --hard origin/main
          npm install --production
          
          # Restart the app (using 'server' as the name)
          pm2 restart server || pm2 start server.js --name "server"
          pm2 save
